# Generated by Django 4.0 on 2022-01-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
